name: Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    secrets:
      access-token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets:
      token: ${{ secrets.TF_API_TOKEN }}
    permissions:
      pull-requests: write
  aws:
    if: ${{ !github.event.issue.pull_request }}
    needs: terraform
    uses: ./.github/workflows/aws.yml