name: Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    secrets:
      access-token:
        required: true
      aws-access-key:
        required: true
      aws-secret-key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  terraform:
    uses: ./.github/workflows/terraform.yml
    secrets:
      access-token: ${{ secrets.TF_API_TOKEN }}
    permissions:
      pull-requests: write

  aws:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: terraform
    uses: ./.github/workflows/aws.yml
    secrets:
      aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}